### ISSUE TITLE
Led Strip "Armed state + Warning" becomes "Armed state + Blink on landing" after save

### ISSUE THREAD

**Issue by PascalRZ** [betaflight/betaflight-configurator#1222]
Hi all and congratulations to Betaflight / BFConfigurator developers for your job !

In Betaflight Configurator, in Led Strip menu, when I select my LED and select "Armed State" in base function and "Warnings" in overlays, each time I save it, each time my Eachine X220S / OMNIBUSF4SD 3.1.7 gets in memory "Armed State" and "Blink on landing". The only way to save it correctly is to go to the CLI and manually add AW argument (instead of AN)

Because I can configure properly my quad with the CLI, I think the bug is in BFConfigurator and not in BF.

PascalRZ

**Comment by mikeller** [comment]
@PascalRZ: The 3.1.7 firmware is pretty old, and there is no obvious bug causing this. I don't think it makes sense to spend a lot of time trying to find and fix this bug - you can either use the CLI to configure LED_STRIP in 3.1.7, or you can update to a more recent version of the firmware that does not have this bug (and has lots of other improvements :wink:).

**Comment by mikeller** [comment]
@PascalRZ: I verified that the bug does not exist in 3.5.2.

Fair enough if you are happy with and want to keep using 3.1.7, and accept that bugs in it will only be fixed in newer versions - that's the only realistic thing to do for a community project with limited resources. (Still, there have been a lot of flight performance improvements in 3.4 and 3.5, so I believe that if you gave a newer version a go you'd find that it flies even better than 3.1.7. :wink: And if you keep the output of `diff all` from 3.1.7 you can always go back to it and restore it to how it was if you don't like the newer version.)

And yes please, close this issue.
