### ISSUE TITLE
OSD element "RSSI DBM Value" needs to be added to configurator

### ISSUE THREAD

**Issue by Docteh** [betaflight/betaflight-configurator#1490]
https://github.com/betaflight/betaflight/pull/8309

That commit adds an element `OSD_RSSI_DBM_VALUE`, an alarm, and a warning. 
`OSD_STAT_MIN_RSSI_DBM` an item for Flight Stats. not sure why that one isn't showing up on the OSD tab as an Unknown

`preview: FONT.symbol(SYM.RSSI) + '-130'`

default alarm appears to be 60, which would display as -60

**Comment by McGiverGim** [comment]
Yes, I saw it yesterday. Any OSD element that has not been added to the Configurator appears as unknown. Is a way to not forgot any before the next release :)

I didn't add it yesterday because I prefer to merge first this: https://github.com/betaflight/betaflight-configurator/pull/1487 if not it will conflict.

But is good to have it here as an issue to not forgot about it 😄

**Comment by mikeller** [comment]
#1487 has been merged.

**Comment by McGiverGim** [comment]
I created the PR with the preview and the warning. I can't add the alarm because it needs to be added to the MSP first.
