### ISSUE TITLE
VTX table - how to input only one band?

### ISSUE THREAD

**Issue by laurentopia** [betaflight/betaflight-configurator#1744]
I only use A4, how do I input that in the table?
![image](https://user-images.githubusercontent.com/26075468/66723402-85c6fd00-edcd-11e9-9522-c286e0284160.png)
this doesn't work, the vtx remains at R1

**Comment by Anisotropic** [comment]
You configured A band with 1 channels with frequency 4. If you want A4 = you need to input 4 channels per band and in 4 channel (last) you need to put your frequency

**Comment by IvoFPV** [comment]
You can just set the frequency of A4 channel instead of 4. Also your power values are wrong.
Please don't open an issue regarding this. This is a configuration issue and not a right place to get help. You can join our Slack where you can ask these kind of questions and get the answer much quicker. https://slack.betaflight.com/

**Comment by mikeller** [comment]
@laurentopia: Try this: 
[vtxtable.json.txt](https://github.com/betaflight/betaflight-configurator/files/3728668/vtxtable.json.txt)

**Comment by laurentopia** [comment]
> @laurentopia: Try this:
> [vtxtable.json.txt](https://github.com/betaflight/betaflight-configurator/files/3728668/vtxtable.json.txt)

cool, this helps and so this should be the default.
