### ISSUE TITLE
Flashing in the android app??

### ISSUE THREAD

**Issue by butterSnake** [betaflight/betaflight-configurator#2340]
Is this possible as a feature ?

**Comment by Asizon** [comment]
I think @WalcoFPV tried to implement it, but there are something dificult in this implementation. But it should be possible using a Cordova plugin for stm flashings.

**Comment by mikeller** [comment]
Yeah, the problem is that there is no native driver for the STM DFU mode USB device in Android (as opposed to the ACM device that the USB port registers as when Betaflight is running).
So in order to make this work we'd have to implement and maintain an Android low level driver, which is considerably more involved than maintaining an android application.

**Comment by UnklBilly1** [comment]
I'm just trying to get my drone to fly. I don't know what any of this means.

**Comment by sugaarK** [comment]
> I'm just trying to get my drone to fly. I don't know what any of this means.

Use a computer not a fone

**Comment by haslinghuis** [comment]
Not possible
