### ISSUE TITLE
LED Tab is broken

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#2359]
since #2319 the LED tab is brocken ... @haslinghuis pls can you check whats wrong

After selecting the tab the configurator hangs, only a disconnect brings the configurator back to work again.

befor this pr: 
![befor](https://user-images.githubusercontent.com/29702171/103222853-4084e180-4925-11eb-8cb8-6c9d87f274e3.jpg)

after this pr:
![after](https://user-images.githubusercontent.com/29702171/103222873-4aa6e000-4925-11eb-8258-121f44f26639.jpg)

**Comment by haslinghuis** [comment]
@TheIsotopes Are there any `console.log()` messages ? (F12) 
If it hangs there is probably a undefined value.

**Comment by TheIsotopes** [comment]
@haslinghuis here the console output:

![console_log](https://user-images.githubusercontent.com/29702171/103274769-c145eb00-49c2-11eb-9984-68588a4b86e2.png)

**Comment by haslinghuis** [comment]
Moving line 71 to line 12 should resolve this. Are you able to check this change before I create a bugfix?

**Comment by TheIsotopes** [comment]
ok, doesn't get stuck anymore ... but the functions and overlays of the LED's are not displayed (see first screenshot above)

![new_led_tab](https://user-images.githubusercontent.com/29702171/103280171-00c70400-49d0-11eb-9562-f59c8f69fe50.jpg)

**Comment by haslinghuis** [comment]
Okay can reproduce. Initial it's working but after save and revisiting it does not display the functions / overlay.

**Comment by haslinghuis** [comment]
@TheIsotopes - I just reverted the `led_strip.js` on `master` from another working tree and it behaves exactly the same as this issue linked PR. With the last changes after saving the LEDs the colors are back but I can't see any of the overlay functions I have set. But this is also what I see with previous version.
The bug seems to be an extra or missing starting dot in the jQuery selector element. Found some other issues but they already were there before my change so this wouldn't have caused impact. Please could you test my last change in the linked PR.

**Comment by TheIsotopes** [comment]
You are right, it is displayed correctly but after changing and saving the wrong information is displayed.

**Comment by haslinghuis** [comment]
@TheIsotopes - Could you please test again?

**Comment by TheIsotopes** [comment]
@haslinghuis Now everything seems to work as usual again. 👍
