### ISSUE TITLE
BF Config suddenly stops opening/ taskbar hover preview is blank

### ISSUE THREAD

**Issue by LAWMAN-FPV** [betaflight/betaflight-configurator#2410]
BF Configurator 10.7 was working for months and suddenly stopped. Program won't load beyond placing icon in task bar. 
No hardware changes. May have been a windows update? 

Tried reinstall and the --disable-gpu from a few years back but that did not work either. 
Please advise on what else I should place here to diagnose. 
Thanks and sorry if I offended any rules. First timer here.
![BF Taskbar Preview](https://user-images.githubusercontent.com/79033327/107868128-afb78600-6e3e-11eb-8451-13c5631cde40.jpg)

**Comment by mikeller** [comment]
It would help if you specified what operating system you are using.

**Comment by LAWMAN-FPV** [comment]
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042

**Comment by mikeller** [comment]
@LAWMAN-FPV: Try uninstalling configurator, then deleting the `C:\Users\${USERNAME})\AppData\Local\betaflight-configurator` directory, and then installing it again.

**Comment by LAWMAN-FPV** [comment]
That seems to have solved the issue. Thank you!

**Comment by mikeller** [comment]
Nothing much to explain - this is the directory where the framework used for configurator stores its configuration and cache. Sometimes this data gets corrupted, and deleting the directory will fix this. (The directory is not deleted during an uninstall / reinstall so that the user's preferences will not be lost in every upgrade.)

**Comment by haslinghuis** [comment]
@LAWMAN-FPV Please close the issue as it's resolved.
