### ISSUE TITLE
Please reintroduce armv7 builds

### ISSUE THREAD

**Issue by IMbackK** [betaflight/betaflight-configurator#2984]
### Is your feature request related to a problem? Please describe

The configuratior is broken on armv7, sutch as many postmarketos devices for no good reason. The armv7 target was simply replaced by an armv8 target, it is highly dubious why this is nessecary vs just having another target.

### Describe the solution you'd like

Please revert 3f0a4568e4ab97b53c9e5f0e8861b2c09ae50e70, as all current armv8 devices can run armv7 software. the reverse is not true

### Describe alternatives you've considered

If native armv8 support is desired please do this via a separate target instead.

**Comment by gandlers** [comment]
"Please revert https://github.com/betaflight/betaflight-configurator/commit/3f0a4568e4ab97b53c9e5f0e8861b2c09ae50e70, as all current armv8 devices can run armv7 software. the reverse is not true"

While 64bit ARM CPUs can execute 32bit code it relies on the OS having the 32bit  support.
I was unable to run armv7 build of the configurator (10.7.x) on my pinebook-pro running ManjaroARM (64bit) as there is no 32 bit support enabled in the OS.
It is possible to "run" the configurator without building the release  ("yarn gulp release --armv7") which is how I got 10.7 working on armv8 CPU before the change from armv7 to armv8. (but the armv8 target doesnt work for v10.8 at the moment dues to changes in the downloaded NWJS binaries)
As long as you have a working NW binary for your system you can build from source with the "yarn gulp dist" then cd to the dist folder and launch the configurator using "nw ."

Here is a link to how i got RC2 working on my setup but will be the same for armv7, just use the armv7 binaries for node and nwjs rather than armv8 as I used.
http://www.gandytech.co.uk/blog/betaflight-configurator-on-manjaro-linux-arm64/
