### ISSUE TITLE
Windows 7 incompatability

### ISSUE THREAD

**Issue by STONEWULFF** [betaflight/betaflight-configurator#3033]
### Is your feature request related to a problem? Please describe

I am new to Github and not a coder at all, i hope this is the place t0 mention this. I help people to get their birds in the air here in my small town and use an old laptop running Win7Pro. up until today i have been fine using beta-flight configurator....10.8.0 has me in a bind and unable to fix the problem without reverting to older firmware which my client is not super impressed by. I can make it work for now however felt it was a viable mention.

### Describe the solution you'd like

add reverse compatability for 10.8.0 on Windows7 and 7Pro

### Describe alternatives you've considered

Reverting to older firmware or to Emuflight as i am well versed in its uses and solutions and the community to find solution's through....as i believe are likely the same circles.

**Comment by McGiverGim** [comment]
I don't understand the message. You are talking about firmware not compatible? Or about the configurator not compatible?
The firmware has nothing to do with the OS. The configurator is not officially supported because we use some libraries that are not officially compatible. You can install the portable version and check, but it does not depend of us.
