### ISSUE TITLE
Problem with OSD configuration

### ISSUE THREAD

**Issue by sebastianha** [betaflight/betaflight-configurator#309]
I enabled OSD in the configurator but I cannot use the OSD tab as it is not properly displayed (see screenshot):

![screenshot16](https://cloud.githubusercontent.com/assets/420807/19127734/97529144-8b40-11e6-92d1-31af31da419c.png)

I am running betaflight 3.0.0 with configurator 1.8.1 (master had the same problem) on a naze32 and a micro-minimosd with the latest software. The OSD is connected through soft-serial and running a 19200 baud.

Can anyone reproduce this problem?

**Comment by nathantsoi** [comment]
Yeah, that's not going to work. The osd tab only works with the betaflight
osd (max7456 integrated via spi)

I'm surprised the osd tab was visible at all?

**Comment by sebastianha** [comment]
Ah, ok. I thought it will also work with minimosd. I had to enable OSD to use the OSD-Mode (see #251)

Thanks for the quick answer!

**Comment by mikeller** [comment]
@nathantsoi : 

> I'm surprised the osd tab was visible at all?

I think this is caused by configurator not understanding the format of the OSD related MSP commands for firmware that was compiled without OSD support, and throwing exceptions. Probably better make the commands entirely conditional in the firmware (giving you 'unknown MSP command' instead of an exception), or make the configurator understand the syntax.

**Comment by mactac** [comment]
I am having this exact problem, however I am using a betaflight F3 board.   My computer displays fine, but my android tablet does not, it displays exactly as the one above.
