### ISSUE TITLE
Odd behaviour when toggling 'Release' and 'Release and Release Candidates'

### ISSUE THREAD

**Issue by hydra** [betaflight/betaflight-configurator#3171]
### Describe the bug

UI elements shown incorrectly.

### To Reproduce

When you first select 'Release and Release Candidate' the UI looks like this:

![image](https://user-images.githubusercontent.com/57075/209669707-a997072e-0f69-4e4d-ad34-e14292761266.png)

If you then toggle classic mode it looks like this:

![image](https://user-images.githubusercontent.com/57075/209670003-0620d530-df8f-4350-aa3f-b31f93797210.png)
a

If you then select 'Release' it looks like this:

![image](https://user-images.githubusercontent.com/57075/209669890-01891413-8ccb-4306-80e6-5e974c315b17.png)

When you select 'Release and Release Candidate' again the UI looks like this:

![image](https://user-images.githubusercontent.com/57075/209669210-4f247a62-c8bc-4093-9837-281820324d61.png)

### Expected behavior

Consistent UI elements based on selections.

### Configurator version

10.9.0-debug-23b74d99

**Comment by blckmn** [comment]
This is currently because there is no cloud build release that is classified as a release.

Once 4.4.0 is released then the UI will function as expected.

For clarity, 4.3.2 or lower is not cloud built, but rather uses the pre built targets. Therefore there's no need to show the option panel as it serves no purpose.

**Comment by hydra** [comment]
@blckmn This seems to be fixed now.  I just updated `master` and I'm unable to reproduce this.
