### ISSUE TITLE
GPS waiting info in wrong position

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#3524]
### Describe the bug

see the screenshot

![Screenshot 2023-07-22 085216](https://github.com/betaflight/betaflight-configurator/assets/29702171/7ccfb7ec-3658-47fe-9380-0411b2a6812e)

### To Reproduce

using latest configurator 10.10

### Expected behavior

info in right position

### Configurator version

10.10

**Comment by haslinghuis** [comment]
Shows like this on Linux:

![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/cfcb0d96-d979-40cc-809d-c2284b843067)

![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/326080b7-51d9-4c0c-a47b-1b4bf9e4e249)

![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/b12073fa-e013-4605-a0b0-27bc4599511a)

Margin-top needs to be 30% for 1920*1080 instead of 50% (tested on 1280*1024)

![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/0dcc8a43-3bbd-439b-85aa-4b31b01cdb84)

**Comment by TheIsotopes** [comment]
ok. with `margin-top: 30%;` it looks good 👍

**Comment by HThuren** [comment]
Good idea, I have never seen this text :-)
