### ISSUE TITLE
GPS Tab Not Show SAT Status while GPS IS fixed

### ISSUE THREAD

**Issue by ChrisSFPV** [betaflight/betaflight-configurator#3699]
### Describe the bug

The GPS Tab dont Show SAT Status,Signal strength or SAT ID . I used bf4.5 and Portable 10.10 configurator 

### To Reproduce

https://github.com/betaflight/betaflight-configurator/assets/123232353/48fb8b7e-256c-4fa8-9bee-ba55498bb4a9

![17036827502981837081837315068417](https://github.com/betaflight/betaflight-configurator/assets/123232353/1197a7d9-1dfa-4ec8-94dc-de9a8c7abc19)

### Expected behavior

Wanted to se SAT Status and Signal strength 

### Configurator version

10.10.0-rc1 Portable

**Comment by asudhir1947** [comment]
I see the same issue. When my quad was on 4.4, and I connected to the configurator 4.5 rc1, I was able to see all the gps stats information, but once I upgraded my quad to 4.5 rc1, i stopped seeing the gps stats as the above poster, is it something to do with the fc no requesting the information when in flight mode ? ( from wiki - If the FC is connected to Configurator at boot time, we request the full satellite information list, so that we can populate the detailed satellite information list on the left side of Configurator's GPS tab. Otherwise this information is not requested, because we do not require it while in flight, and it adds a lot of serial port traffic when enabled.)

**Comment by haslinghuis** [comment]
Fixed in firmware-zulu as configurator had a build for enabling the sats using a MSP command as we changed implementation.

Nightly configurator and firmware-zulu will work as RC2 is around the corner.
