### ISSUE TITLE
Configurator 3.2.1 -  OSD Preview does not reflect updated Fonts

### ISSUE THREAD

**Issue by 1xGSEadamx** [betaflight/betaflight-configurator#604]
Configurator Version: 3.2.1
Board: DYSF4Pro
Release: 3.2 RC3

**Steps to recreate:**
Click OSD Tab
Click Font Manager
Click Digital Font
Click Upload
**Expected Result**: Font in OSD preview should reflected uploaded font.
**Actual Result:** OSD preview reflects original font.

**Comment by jflyper** [comment]
@1xGSEadamx Not reproducible. All Fonts uploads and displayed without a problem.

![betaflight_-_configurator](https://user-images.githubusercontent.com/14850998/29203197-1f885492-7eaa-11e7-90c5-0af10dc456e0.jpg)

Default
![img_7321](https://user-images.githubusercontent.com/14850998/29203373-5e5fa6ec-7eab-11e7-812c-f0bbfb9cdb10.JPG)

Bold
![img_7322](https://user-images.githubusercontent.com/14850998/29203377-6bc830e2-7eab-11e7-85b3-26898f8c0f8f.JPG)

Large
![img_7323](https://user-images.githubusercontent.com/14850998/29203390-7b064d32-7eab-11e7-95c4-1c3455b2e019.JPG)

Extra Large
![img_7324](https://user-images.githubusercontent.com/14850998/29203406-870c7f20-7eab-11e7-8238-b08a0e7cd89e.JPG)

Betaflight
![img_7325](https://user-images.githubusercontent.com/14850998/29203413-916ec734-7eab-11e7-8df1-dc0601e6f18e.JPG)

Digital
![img_7326](https://user-images.githubusercontent.com/14850998/29203415-9a6cc7e6-7eab-11e7-8d04-f065168fc521.JPG)

**Comment by 1xGSEadamx** [comment]
@jflyper Strange - when I upload the font, the board reboots after the progress bar completes but the change is not saved. Also revisiting the OSD tab in betaflight shows the old font.

**Comment by Arakon** [comment]
Works here on 3 boards too. Did you actually check the font change on screen? The preview screen does NOT properly reflect the active font.
Also, make sure your OSD is getting enough power through your USB port.. some standalone OSDs had trouble with the font upload if they didn't get a stable voltage.

**Comment by 1xGSEadamx** [comment]
Retested and the font is reflected on the actual OSD but the preview is not updating. Updating Issue details

**Comment by Arakon** [comment]
Problem with that is, that there is no way for the configurator to actually know what font is loaded on the OSD.

**Comment by basdelfos** [comment]
The configurator and BF don't know which font is uploaded. Maybe good to
add a message to inform the shown font in de configurator OSD preview is no
an actual reflection of the installed font.

Op 14 aug. 2017 6:11 a.m. schreef "1xGSEadamx" <notifications@github.com>:

**Comment by tigert** [comment]
A workaround (when I worked on my own font) is to upload it, then reconnect and go to font uploader, select the font and then cancel the upload. A bit cumbersome, but the font gets loaded into configurator, and at least you can see your font on the virtual OSD without needing a quad with all the features working.

I guess it could be solved with an "uploaded font" setting in betaflight, which would be a bit sketchy since it would not really be a real setting, rather than a stored piece of information. I guess you could store the path to the last font you uploaded and reload it when you connect a board, which of course would work only on the same computer you uploaded the font with.
