### ISSUE TITLE
Restore button does not work in 3.2RC5

### ISSUE THREAD

**Issue by RaceFPV** [betaflight/betaflight-configurator#668]
The backup file gets properly created, but when restore is attempted it does not restore the previous config state. Restore will prompt for the restore file, accept it, log `Configuration migration complete, migrations applied: 2`, but the config is never actually restored.

**Comment by MR444** [comment]
I have the same problem after flashing from 3.1.5 to 3.2.0. Size of json files is always 33KB. Restoring backup files does not change anything.

**Comment by mikeller** [comment]
Fixed by #647 (still needs to be released to the Chrome web store).

**Comment by dthubereng** [comment]
I noticed the same thing as the OP on 3.2.2.

Restore works mostly in 10.0.0 for me with the exception that it doesn't restore everything. So far, I've noticed it doesn't restore ESC/motor protocol and yaw position (haven't looked at the other positions because yaw is the only one I have to adjust on my build). I've checked this with both Mac OS X High Sierra and Win 10.

**Comment by mikeller** [comment]
@dthubereng: The way the save / restore buttons work is not done in a great way, since it relies on all of the data explicitly being polled from the flight controller before serialising and saving, and then being pushed after loading. I'll look into adding the missing MSP calls for this (or you can if you want to).
In the mean time, use the CLI for back ups / restores.

**Comment by dthubereng** [comment]
not real familiar with js, but I've been looking at the backup_restore functions to see where the missing calls are.

**Comment by mikeller** [comment]
@dthubereng: No problem then, I can do it. `backup_restore.js` isn't exactly the best place to be doing a deep dive into JS.
