### ISSUE TITLE
Update warnings on firmware flasher page

### ISSUE THREAD

**Issue by mawais15** [betaflight/betaflight-configurator#818]
Some warnings on firmware flasher still showing chrome related stuff like "If you have problems flashing try disconnecting all cables from your FC first, try rebooting, **upgrade chrome**, upgrade drivers"
I think upgrading chrome is no more required because its a standalone application now.

**Comment by mikeller** [comment]
Thanks for reporting this. We are still in the process of ironing out the details of the switch to a standalone application, and we will be amending the documentation when we get to it.

(Also, take note that the Chrome web store version of the configurator will be maintained for now, since it still works on Chromebooks, which some people use to configure their craft while on the airfield.)

**Comment by danybd** [comment]
@mikeller Issue outdated? Should be closed as no more chrome support?

**Comment by mikeller** [comment]
@danybd: No, in fact the messages referring to Chrome are still in the application and by now they should be removed:

![image](https://user-images.githubusercontent.com/4742747/111311538-37551680-86c3-11eb-85e7-fd38b1dcd229.png)
